apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-pv-claim
  namespace: ntfy
  labels:
    app: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi